import { Attribute, Hero } from './types';

// Using Valve's official CDN which is highly reliable for these internal hero names
export const getHeroImageUrl = (slug: string) => `https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/${slug}_full.png`;

// Using Valve's official CDN for items
export const getItemImageUrl = (slug: string) => `https://steamcdn-a.akamaihd.net/apps/dota2/images/items/${slug}_lg.png`;

export const HEROES: Hero[] = [
  // STRENGTH
  { id: 1, name: 'Alchemist', attribute: Attribute.STRENGTH, roles: ['Carry', 'Support', 'Nuker'], img: 'alchemist' },
  { id: 2, name: 'Axe', attribute: Attribute.STRENGTH, roles: ['Initiator', 'Durable', 'Carry'], img: 'axe' },
  { id: 3, name: 'Bristleback', attribute: Attribute.STRENGTH, roles: ['Carry', 'Durable', 'Nuker'], img: 'bristleback' },
  { id: 4, name: 'Centaur Warrunner', attribute: Attribute.STRENGTH, roles: ['Initiator', 'Durable', 'Nuker'], img: 'centaur' },
  { id: 5, name: 'Chaos Knight', attribute: Attribute.STRENGTH, roles: ['Carry', 'Initiator', 'Durable'], img: 'chaos_knight' },
  { id: 6, name: 'Dawnbreaker', attribute: Attribute.STRENGTH, roles: ['Carry', 'Durable'], img: 'dawnbreaker' },
  { id: 7, name: 'Doom', attribute: Attribute.STRENGTH, roles: ['Carry', 'Initiator', 'Disabler'], img: 'doom_bringer' },
  { id: 8, name: 'Dragon Knight', attribute: Attribute.STRENGTH, roles: ['Carry', 'Pusher', 'Durable'], img: 'dragon_knight' },
  { id: 9, name: 'Earth Spirit', attribute: Attribute.STRENGTH, roles: ['Nuker', 'Escape', 'Disabler'], img: 'earth_spirit' },
  { id: 10, name: 'Earthshaker', attribute: Attribute.STRENGTH, roles: ['Support', 'Initiator', 'Disabler'], img: 'earthshaker' },
  { id: 11, name: 'Elder Titan', attribute: Attribute.STRENGTH, roles: ['Initiator', 'Disabler', 'Nuker'], img: 'elder_titan' },
  { id: 12, name: 'Huskar', attribute: Attribute.STRENGTH, roles: ['Carry', 'Durable', 'Initiator'], img: 'huskar' },
  { id: 13, name: 'Kunkka', attribute: Attribute.STRENGTH, roles: ['Carry', 'Initiator', 'Disabler'], img: 'kunkka' },
  { id: 14, name: 'Legion Commander', attribute: Attribute.STRENGTH, roles: ['Carry', 'Disabler', 'Initiator'], img: 'legion_commander' },
  { id: 15, name: 'Lifestealer', attribute: Attribute.STRENGTH, roles: ['Carry', 'Durable', 'Escape'], img: 'life_stealer' },
  { id: 16, name: 'Mars', attribute: Attribute.STRENGTH, roles: ['Initiator', 'Durable', 'Disabler'], img: 'mars' },
  { id: 17, name: 'Night Stalker', attribute: Attribute.STRENGTH, roles: ['Carry', 'Initiator', 'Durable'], img: 'night_stalker' },
  { id: 18, name: 'Ogre Magi', attribute: Attribute.STRENGTH, roles: ['Support', 'Nuker', 'Disabler'], img: 'ogre_magi' },
  { id: 19, name: 'Omniknight', attribute: Attribute.STRENGTH, roles: ['Support', 'Durable', 'Nuker'], img: 'omniknight' },
  { id: 20, name: 'Primal Beast', attribute: Attribute.STRENGTH, roles: ['Initiator', 'Durable', 'Disabler'], img: 'primal_beast' },
  { id: 21, name: 'Pudge', attribute: Attribute.STRENGTH, roles: ['Disabler', 'Initiator', 'Durable'], img: 'pudge' },
  { id: 22, name: 'Slardar', attribute: Attribute.STRENGTH, roles: ['Carry', 'Initiator', 'Disabler'], img: 'slardar' },
  { id: 23, name: 'Spirit Breaker', attribute: Attribute.STRENGTH, roles: ['Initiator', 'Durable', 'Escape'], img: 'spirit_breaker' },
  { id: 24, name: 'Sven', attribute: Attribute.STRENGTH, roles: ['Carry', 'Disabler', 'Initiator'], img: 'sven' },
  { id: 25, name: 'Tidehunter', attribute: Attribute.STRENGTH, roles: ['Initiator', 'Durable', 'Disabler'], img: 'tidehunter' },
  { id: 26, name: 'Tiny', attribute: Attribute.STRENGTH, roles: ['Carry', 'Nuker', 'Initiator'], img: 'tiny' },
  { id: 27, name: 'Treant Protector', attribute: Attribute.STRENGTH, roles: ['Support', 'Initiator', 'Durable'], img: 'treant' },
  { id: 28, name: 'Tusk', attribute: Attribute.STRENGTH, roles: ['Initiator', 'Disabler', 'Nuker'], img: 'tusk' },
  { id: 29, name: 'Underlord', attribute: Attribute.STRENGTH, roles: ['Support', 'Nuker', 'Durable'], img: 'abyssal_underlord' },
  { id: 30, name: 'Undying', attribute: Attribute.STRENGTH, roles: ['Support', 'Durable', 'Disabler'], img: 'undying' },
  { id: 31, name: 'Wraith King', attribute: Attribute.STRENGTH, roles: ['Carry', 'Support', 'Durable'], img: 'skeleton_king' },

  // AGILITY
  { id: 32, name: 'Anti-Mage', attribute: Attribute.AGILITY, roles: ['Carry', 'Escape', 'Nuker'], img: 'antimage' },
  { id: 33, name: 'Arc Warden', attribute: Attribute.AGILITY, roles: ['Carry', 'Escape', 'Nuker'], img: 'arc_warden' },
  { id: 34, name: 'Bloodseeker', attribute: Attribute.AGILITY, roles: ['Carry', 'Disabler', 'Jungler'], img: 'bloodseeker' },
  { id: 35, name: 'Bounty Hunter', attribute: Attribute.AGILITY, roles: ['Escape', 'Nuker'], img: 'bounty_hunter' },
  { id: 36, name: 'Clinkz', attribute: Attribute.AGILITY, roles: ['Carry', 'Escape', 'Pusher'], img: 'clinkz' },
  { id: 37, name: 'Drow Ranger', attribute: Attribute.AGILITY, roles: ['Carry', 'Disabler', 'Pusher'], img: 'drow_ranger' },
  { id: 38, name: 'Ember Spirit', attribute: Attribute.AGILITY, roles: ['Carry', 'Escape', 'Nuker'], img: 'ember_spirit' },
  { id: 39, name: 'Faceless Void', attribute: Attribute.AGILITY, roles: ['Carry', 'Initiator', 'Disabler'], img: 'faceless_void' },
  { id: 40, name: 'Gyrocopter', attribute: Attribute.AGILITY, roles: ['Carry', 'Nuker', 'Disabler'], img: 'gyrocopter' },
  { id: 41, name: 'Hoodwink', attribute: Attribute.AGILITY, roles: ['Support', 'Nuker', 'Escape'], img: 'hoodwink' },
  { id: 42, name: 'Juggernaut', attribute: Attribute.AGILITY, roles: ['Carry', 'Pusher', 'Escape'], img: 'juggernaut' },
  { id: 43, name: 'Kez', attribute: Attribute.AGILITY, roles: ['Carry', 'Escape', 'Nuker'], img: 'kez' }, 
  { id: 44, name: 'Luna', attribute: Attribute.AGILITY, roles: ['Carry', 'Nuker', 'Pusher'], img: 'luna' },
  { id: 45, name: 'Medusa', attribute: Attribute.AGILITY, roles: ['Carry', 'Durable'], img: 'medusa' },
  { id: 46, name: 'Meepo', attribute: Attribute.AGILITY, roles: ['Carry', 'Escape', 'Nuker'], img: 'meepo' },
  { id: 47, name: 'Monkey King', attribute: Attribute.AGILITY, roles: ['Carry', 'Escape', 'Disabler'], img: 'monkey_king' },
  { id: 48, name: 'Morphling', attribute: Attribute.AGILITY, roles: ['Carry', 'Escape', 'Nuker'], img: 'morphling' },
  { id: 49, name: 'Naga Siren', attribute: Attribute.AGILITY, roles: ['Carry', 'Support', 'Pusher'], img: 'naga_siren' },
  { id: 50, name: 'Phantom Assassin', attribute: Attribute.AGILITY, roles: ['Carry', 'Escape'], img: 'phantom_assassin' },
  { id: 51, name: 'Phantom Lancer', attribute: Attribute.AGILITY, roles: ['Carry', 'Escape', 'Pusher'], img: 'phantom_lancer' },
  { id: 52, name: 'Razor', attribute: Attribute.AGILITY, roles: ['Carry', 'Durable', 'Nuker'], img: 'razor' },
  { id: 53, name: 'Riki', attribute: Attribute.AGILITY, roles: ['Carry', 'Escape', 'Disabler'], img: 'riki' },
  { id: 54, name: 'Shadow Fiend', attribute: Attribute.AGILITY, roles: ['Carry', 'Nuker'], img: 'nevermore' },
  { id: 55, name: 'Slark', attribute: Attribute.AGILITY, roles: ['Carry', 'Escape', 'Disabler'], img: 'slark' },
  { id: 56, name: 'Sniper', attribute: Attribute.AGILITY, roles: ['Carry', 'Nuker'], img: 'sniper' },
  { id: 57, name: 'Spectre', attribute: Attribute.AGILITY, roles: ['Carry', 'Durable', 'Escape'], img: 'spectre' },
  { id: 58, name: 'Templar Assassin', attribute: Attribute.AGILITY, roles: ['Carry', 'Escape'], img: 'templar_assassin' },
  { id: 59, name: 'Terrorblade', attribute: Attribute.AGILITY, roles: ['Carry', 'Pusher', 'Nuker'], img: 'terrorblade' },
  { id: 60, name: 'Troll Warlord', attribute: Attribute.AGILITY, roles: ['Carry', 'Pusher', 'Durable'], img: 'troll_warlord' },
  { id: 61, name: 'Ursa', attribute: Attribute.AGILITY, roles: ['Carry', 'Jungler', 'Durable'], img: 'ursa' },
  { id: 62, name: 'Viper', attribute: Attribute.AGILITY, roles: ['Carry', 'Durable', 'Initiator'], img: 'viper' },
  { id: 63, name: 'Weaver', attribute: Attribute.AGILITY, roles: ['Carry', 'Escape'], img: 'weaver' },

  // INTELLIGENCE
  { id: 64, name: 'Ancient Apparition', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Disabler', 'Nuker'], img: 'ancient_apparition' },
  { id: 65, name: 'Crystal Maiden', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Disabler', 'Nuker'], img: 'crystal_maiden' },
  { id: 66, name: 'Death Prophet', attribute: Attribute.INTELLIGENCE, roles: ['Carry', 'Pusher', 'Nuker'], img: 'death_prophet' },
  { id: 67, name: 'Disruptor', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Disabler', 'Initiator'], img: 'disruptor' },
  { id: 68, name: 'Enchantress', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Jungler', 'Durable'], img: 'enchantress' },
  { id: 69, name: 'Grimstroke', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Nuker', 'Disabler'], img: 'grimstroke' },
  { id: 70, name: 'Jakiro', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Nuker', 'Pusher'], img: 'jakiro' },
  { id: 71, name: 'Keeper of the Light', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Nuker', 'Disabler'], img: 'keeper_of_the_light' },
  { id: 72, name: 'Leshrac', attribute: Attribute.INTELLIGENCE, roles: ['Carry', 'Support', 'Nuker'], img: 'leshrac' },
  { id: 73, name: 'Lich', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Nuker'], img: 'lich' },
  { id: 74, name: 'Lina', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Carry', 'Nuker'], img: 'lina' },
  { id: 75, name: 'Lion', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Disabler', 'Nuker'], img: 'lion' },
  { id: 76, name: 'Muerta', attribute: Attribute.INTELLIGENCE, roles: ['Carry', 'Nuker', 'Disabler'], img: 'muerta' },
  { id: 77, name: 'Nature\'s Prophet', attribute: Attribute.INTELLIGENCE, roles: ['Carry', 'Jungler', 'Pusher'], img: 'furion' },
  { id: 78, name: 'Necrophos', attribute: Attribute.INTELLIGENCE, roles: ['Carry', 'Nuker', 'Durable'], img: 'necrolyte' },
  { id: 79, name: 'Oracle', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Nuker', 'Disabler'], img: 'oracle' },
  { id: 80, name: 'Outworld Destroyer', attribute: Attribute.INTELLIGENCE, roles: ['Carry', 'Nuker', 'Disabler'], img: 'obsidian_destroyer' },
  { id: 81, name: 'Puck', attribute: Attribute.INTELLIGENCE, roles: ['Initiator', 'Disabler', 'Nuker'], img: 'puck' },
  { id: 82, name: 'Pugna', attribute: Attribute.INTELLIGENCE, roles: ['Nuker', 'Pusher'], img: 'pugna' },
  { id: 83, name: 'Queen of Pain', attribute: Attribute.INTELLIGENCE, roles: ['Carry', 'Nuker', 'Escape'], img: 'queenofpain' },
  { id: 84, name: 'Ringmaster', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Disabler', 'Escape'], img: 'ringmaster' },
  { id: 85, name: 'Rubick', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Disabler', 'Nuker'], img: 'rubick' },
  { id: 86, name: 'Shadow Demon', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Disabler', 'Initiator'], img: 'shadow_demon' },
  { id: 87, name: 'Shadow Shaman', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Pusher', 'Disabler'], img: 'shadow_shaman' },
  { id: 88, name: 'Silencer', attribute: Attribute.INTELLIGENCE, roles: ['Carry', 'Support', 'Disabler'], img: 'silencer' },
  { id: 89, name: 'Skywrath Mage', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Nuker', 'Disabler'], img: 'skywrath_mage' },
  { id: 90, name: 'Storm Spirit', attribute: Attribute.INTELLIGENCE, roles: ['Carry', 'Escape', 'Nuker'], img: 'storm_spirit' },
  { id: 91, name: 'Tinker', attribute: Attribute.INTELLIGENCE, roles: ['Carry', 'Nuker', 'Pusher'], img: 'tinker' },
  { id: 92, name: 'Warlock', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Initiator', 'Disabler'], img: 'warlock' },
  { id: 93, name: 'Witch Doctor', attribute: Attribute.INTELLIGENCE, roles: ['Support', 'Nuker', 'Disabler'], img: 'witch_doctor' },
  { id: 94, name: 'Zeus', attribute: Attribute.INTELLIGENCE, roles: ['Nuker'], img: 'zuus' },

  // UNIVERSAL
  { id: 95, name: 'Abaddon', attribute: Attribute.UNIVERSAL, roles: ['Support', 'Carry', 'Durable'], img: 'abaddon' },
  { id: 96, name: 'Bane', attribute: Attribute.UNIVERSAL, roles: ['Support', 'Disabler', 'Nuker'], img: 'bane' },
  { id: 97, name: 'Batrider', attribute: Attribute.UNIVERSAL, roles: ['Initiator', 'Jungler', 'Disabler'], img: 'batrider' },
  { id: 98, name: 'Beastmaster', attribute: Attribute.UNIVERSAL, roles: ['Initiator', 'Disabler', 'Durable'], img: 'beastmaster' },
  { id: 99, name: 'Brewmaster', attribute: Attribute.UNIVERSAL, roles: ['Initiator', 'Durable', 'Nuker'], img: 'brewmaster' },
  { id: 100, name: 'Broodmother', attribute: Attribute.UNIVERSAL, roles: ['Carry', 'Pusher', 'Escape'], img: 'broodmother' },
  { id: 101, name: 'Chen', attribute: Attribute.UNIVERSAL, roles: ['Support', 'Jungler', 'Pusher'], img: 'chen' },
  { id: 102, name: 'Clockwerk', attribute: Attribute.UNIVERSAL, roles: ['Initiator', 'Disabler', 'Durable'], img: 'rattletrap' },
  { id: 103, name: 'Dark Seer', attribute: Attribute.UNIVERSAL, roles: ['Initiator', 'Jungler', 'Escape'], img: 'dark_seer' },
  { id: 104, name: 'Dark Willow', attribute: Attribute.UNIVERSAL, roles: ['Support', 'Nuker', 'Disabler'], img: 'dark_willow' },
  { id: 105, name: 'Dazzle', attribute: Attribute.UNIVERSAL, roles: ['Support', 'Nuker', 'Disabler'], img: 'dazzle' },
  { id: 106, name: 'Enigma', attribute: Attribute.UNIVERSAL, roles: ['Disabler', 'Jungler', 'Initiator'], img: 'enigma' },
  { id: 107, name: 'Invoker', attribute: Attribute.UNIVERSAL, roles: ['Carry', 'Nuker', 'Disabler'], img: 'invoker' },
  { id: 108, name: 'Io', attribute: Attribute.UNIVERSAL, roles: ['Support', 'Escape', 'Nuker'], img: 'wisp' },
  { id: 109, name: 'Lone Druid', attribute: Attribute.UNIVERSAL, roles: ['Carry', 'Pusher', 'Jungler'], img: 'lone_druid' },
  { id: 110, name: 'Lycan', attribute: Attribute.UNIVERSAL, roles: ['Carry', 'Pusher', 'Jungler'], img: 'lycan' },
  { id: 111, name: 'Magnus', attribute: Attribute.UNIVERSAL, roles: ['Initiator', 'Disabler', 'Nuker'], img: 'magnataur' },
  { id: 112, name: 'Marci', attribute: Attribute.UNIVERSAL, roles: ['Support', 'Carry', 'Initiator'], img: 'marci' },
  { id: 113, name: 'Mirana', attribute: Attribute.UNIVERSAL, roles: ['Carry', 'Support', 'Escape'], img: 'mirana' },
  { id: 114, name: 'Nyx Assassin', attribute: Attribute.UNIVERSAL, roles: ['Disabler', 'Nuker', 'Initiator'], img: 'nyx_assassin' },
  { id: 115, name: 'Pangolier', attribute: Attribute.UNIVERSAL, roles: ['Carry', 'Nuker', 'Disabler'], img: 'pangolier' },
  { id: 116, name: 'Phoenix', attribute: Attribute.UNIVERSAL, roles: ['Support', 'Nuker', 'Initiator'], img: 'phoenix' },
  { id: 117, name: 'Sand King', attribute: Attribute.UNIVERSAL, roles: ['Initiator', 'Disabler', 'Nuker'], img: 'sand_king' },
  { id: 118, name: 'Snapfire', attribute: Attribute.UNIVERSAL, roles: ['Support', 'Nuker', 'Disabler'], img: 'snapfire' },
  { id: 119, name: 'Techies', attribute: Attribute.UNIVERSAL, roles: ['Nuker', 'Disabler'], img: 'techies' },
  { id: 120, name: 'Timbersaw', attribute: Attribute.UNIVERSAL, roles: ['Nuker', 'Durable', 'Escape'], img: 'shredder' },
  { id: 121, name: 'Vengeful Spirit', attribute: Attribute.UNIVERSAL, roles: ['Support', 'Initiator', 'Disabler'], img: 'vengefulspirit' },
  { id: 122, name: 'Venomancer', attribute: Attribute.UNIVERSAL, roles: ['Support', 'Nuker', 'Initiator'], img: 'venomancer' },
  { id: 123, name: 'Visage', attribute: Attribute.UNIVERSAL, roles: ['Support', 'Nuker', 'Pusher'], img: 'visage' },
  { id: 124, name: 'Void Spirit', attribute: Attribute.UNIVERSAL, roles: ['Carry', 'Escape', 'Nuker'], img: 'void_spirit' },
  { id: 125, name: 'Windranger', attribute: Attribute.UNIVERSAL, roles: ['Carry', 'Support', 'Escape'], img: 'windrunner' },
  { id: 126, name: 'Winter Wyvern', attribute: Attribute.UNIVERSAL, roles: ['Support', 'Disabler', 'Nuker'], img: 'winter_wyvern' }
];
